### ISSUE TITLE
Add/link to version control module

### ISSUE THREAD

**Issue by bvreede** [carpentries-incubator/lesson-R-packaging#73]
R packaging is enriched substantially if the package is published on github and developed under version control. Fortunately, Rstudio makes this very easy. 
While it need not be implemented in every workshop, it is worthwhile for this lesson to contain an episode on version control, or refer to e.g. [this episode](https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/05-setup-versioning/index.html).

**Comment by f-hafner** [comment]
A possible additional episode for packaging could look like this:
1. Discuss version control briefly, refer to the existing episode for details
2. Highlight the benefits specifically to packaging:
    - github actions: tests run automatically, `R CMD check` on different OSs
    - even if it is just with your lab/small set of co-authors:
        - collaborate: share and integrate contributions
        - communicate with users
            - package website (vignette, function documentation)
            - issues

How hands-on should this be? Since it builds on the existing episode, one may have to go through step 1 in detail before starting on step 2?

I am not sure this fits into this course, but the above made me think a bit more generally about the workflow between package development and research projects. I think the point is how it is useful to separate out the package from the research project, but having them both on a hosted service like github to cross-reference.

For instance, on github you have a repo with the package with all the testing infra etc, and then another repo with the research project (ie, with the paper, presentation, scripts that use the package to make figures and tables etc).
Then, a referee asks you to add some table with more controls in your regression, but for this you need to update the package.
The above set-up allows you to separate the engineering tasks from the research tasks (with issues), but to cross-reference them.
